In [4]:
import pandas as pd

print('sdf')

sdf


In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter'],
    'Age': [28, 24, 35],
    'City': ['New York', 'Paris', 'Berlin']
}

df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   28  New York
1   Anna   24     Paris
2  Peter   35    Berlin


In [6]:
df.size

9

In [7]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
print(df)

    Name  Age      City
0   John   28  New York
1   Anna   24     Paris
2  Peter   35    Berlin


In [9]:
import numpy as np

npdata = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(npdata)
print(npdata.shape)
print(npdata.size)
print(npdata.dtype)
print(npdata.ndim)
print(npdata.itemsize)
print(npdata.nbytes)
print(npdata.T)
print(npdata.flatten())
print(npdata.reshape(1, 9))
print(npdata.reshape(3, 3))
print(npdata.reshape(9, 1))
print(npdata.reshape(3, 3, 1))
print(npdata.reshape(3, 3, 1).shape)
print(npdata.reshape(3, 3, 1).ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2
8
72
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)
3


In [10]:
df = pd.read_csv('./warmup-data/coffee.csv')
print(df)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35


In [11]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['A', 'B', 'C'], index=['x', 'y', 'z'])
print(df)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9


In [12]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes


In [14]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [15]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [16]:
df['A'].unique()

array([1, 4, 7])

In [17]:
df['A'].nunique()

3

In [18]:
df.shape

(3, 3)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes


In [21]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [22]:
coffee.head()

Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [25]:
results = pd.read_parquet('./data/results.parquet')

In [26]:
results.head()

year    type discipline                     event                     as  \
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy   
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy   
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy   
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy   
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy   

   athlete_id  noc             team  place   tied medal  
0           1  FRA             None   17.0   True  None  
1           1  FRA   Jean Montariol    NaN  False  None  
2           1  FRA             None   32.0   True  None  
3           1  FRA  Jeanne Vaussard    8.0   True  None  
4           1  FRA  Jacques Brugnon    4.0  False  None

In [27]:
olympics_data = pd.read_excel('./data/olympics-data.xlsx')

In [28]:
olympics_data.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25

In [29]:
bios = pd.read_csv('./data/bios.csv')
bios.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25

In [30]:
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [31]:
coffee.head()

Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [32]:
coffee.tail()

Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [34]:
coffee.sample(10)

Day Coffee Type  Units Sold
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
0      Monday    Espresso          25
3     Tuesday       Latte          20
7    Thursday       Latte          30
4   Wednesday    Espresso          35
13     Sunday       Latte          35
8      Friday    Espresso          45
5   Wednesday       Latte          25
10   Saturday    Espresso          45

In [35]:
coffee.loc(0)

In [36]:
print(coffee.loc(0))

In [37]:
coffee.head()

Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [39]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [49]:
coffee.iloc[:, [0, 2]]

Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [50]:
coffee.index = coffee['Day']

In [51]:
coffee

Day Coffee Type  Units Sold
Day                                         
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [53]:
coffee.loc['Monday':"Wednesday"]

Day Coffee Type  Units Sold
Day                                         
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [55]:
coffee.loc['Monday', 'Units Sold'] = 20

In [56]:
coffee.loc[:]

Day Coffee Type  Units Sold
Day                                         
Monday        Monday    Espresso          20
Monday        Monday       Latte          20
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25
Thursday    Thursday    Espresso          40
Thursday    Thursday       Latte          30
Friday        Friday    Espresso          45
Friday        Friday       Latte          35
Saturday    Saturday    Espresso          45
Saturday    Saturday       Latte          35
Sunday        Sunday    Espresso          45
Sunday        Sunday       Latte          35

In [57]:
coffee.head()

Day Coffee Type  Units Sold
Day                                         
Monday        Monday    Espresso          20
Monday        Monday       Latte          20
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [67]:
coffee.iat[0, 0]

'Monday'

In [75]:
coffee.sort_values(['Units Sold', 'Coffee Type'], ascending=[0, 1])

Day Coffee Type  Units Sold
Day                                         
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Wednesday  Wednesday       Latte          25
Monday        Monday    Espresso          20
Monday        Monday       Latte          20
Tuesday      Tuesday       Latte          20

Monday Espresso 20

 

Monday Latte 20

 

Tuesday Espresso 30

 

Tuesday Latte 20

 

Wednesday Espresso 35

 

Wednesday Latte 25

 

Thursday Espresso 40

 

Thursday Latte 30

 

Friday Espresso 45

 

Friday Latte 35

 

Saturday Espresso 45

 

Saturday Latte 35

 

Sunday Espresso 45

 

Sunday Latte 35

 



In [79]:
bios.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25

In [80]:
bios.head(10)

athlete_id                   name   born_date          born_city  \
0           1  Jean-François Blanchy  1886-12-12           Bordeaux   
1           2         Arnaud Boetsch  1969-04-01             Meulan   
2           3           Jean Borotra  1898-08-13           Biarritz   
3           4        Jacques Brugnon  1895-05-11        Paris VIIIe   
4           5           Albert Canet  1878-04-17         Wandsworth   
5           6      Nicolas Chatelain  1970-01-13             Amiens   
6           7          Patrick Chila  1969-11-27        Ris-Orangis   
7           8           Henri Cochet  1901-12-14       Villeurbanne   
8           9          Marcel Cousin  1896-08-04              Nîmes   
9          10     Guy de la Chapelle  1868-07-16  Farges-Allichamps   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25  
5                 Somme          FRA  France      181.0       70.0         NaN  
6               Essonne          FRA  France      180.0       73.0         NaN  
7                 Rhône          FRA  France        NaN        NaN  1987-04-02  
8                  Gard          FRA  France        NaN        NaN  1986-08-01  
9                  Cher          FRA  France        NaN        NaN  1923-08-27

In [81]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   athlete_id    145500 non-null  int64  
 1   name          145500 non-null  object 
 2   born_date     143693 non-null  object 
 3   born_city     110908 non-null  object 
 4   born_region   110908 non-null  object 
 5   born_country  110908 non-null  object 
 6   NOC           145499 non-null  object 
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object 
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB


In [83]:
bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]

name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [97]:
bios[bios['name'].str.contains(r'sens$|$sons', case=False, na=False)]

athlete_id                     name   born_date             born_city  \
4692          4709              Ko Janssens  1889-12-20             Rotterdam   
9072          9123           Theo Claessens  1948-12-18                  Niel   
9086          9137         Patrick Hanssens  1956-06-06   Antwerpen (Antwerp)   
13785        13872            Rudi Ceyssens  1962-07-19               Koersel   
13862        13949       Frédéric Claessens  1896-02-09                  Niel   
14790        14890         Bernard Janssens  1895-08-18               Hoboken   
17546        17666         Louis Diercxsens  1898-09-28   Antwerpen (Antwerp)   
17560        17680           Roger Goossens  1926-12-07  Bruxelles (Brussels)   
29192        29406       François Claessens  1897-10-02               Berchem   
29193        29407  Jean-Baptiste Claessens         NaN                   NaN   
32933        33181           Heidi Goossens  1969-04-13             Herentals   
35453        35730             Ben Piessens  1912-02-23              Hemiksem   
40958        41269      Conrad Adriaenssens  1871-09-25   Antwerpen (Antwerp)   
40992        41306          Joseph Janssens         NaN                   NaN   
45107        45450         Colette Goossens  1942-06-02               Roubaix   
45113        45456      Christelle Janssens  1972-02-26                 Arlon   
54841        55235          J. Adriaenssens         NaN                   NaN   
56894        57299           Frits Janssens  1892-03-14               Berchem   
61189        61634            Kurts Klāsens  1893-09-03                  Rīga   
64726        65214          Walter Herssens  1930-02-15       Brugge (Bruges)   
64731        65219          Daniel Janssens  1925-12-02   Petegem-aan-de-Leie   
85457        86138    Jean-Maurice Goossens  1892-01-16               Seraing   
91858        92589              Robert Sens  1977-10-29              Schwerin   
100916      101780            Ward Janssens  1982-07-13       Brugge (Bruges)   
103281      104257     Catriona Oliver-Sens  1980-04-02                  Sale   
123517      125718            Dion Dreesens  1993-04-30                Venray   
130025      132676          Dennis Goossens  1993-12-16               Lokeren   
136428      139654          Sanne Claessens  2004-01-05                   NaN   
138030      141417         Hillary Janssens  1994-07-21                Surrey   
139101      142551            Marc Recasens  1999-09-13             Barcelona   

                         born_region born_country          NOC  height_cm  \
4692                    Zuid-Holland          NED  Netherlands        NaN   
9072                       Antwerpen          BEL      Belgium      188.0   
9086                       Antwerpen          BEL      Belgium      184.0   
13785                        Limburg          BEL      Belgium      189.0   
13862                      Antwerpen          BEL      Belgium        NaN   
14790                      Antwerpen          BEL      Belgium        NaN   
17546                      Antwerpen          BEL      Belgium        NaN   
17560   Région de Bruxelles-Capitale          BEL      Belgium      182.0   
29192                      Antwerpen          BEL      Belgium        NaN   
29193                            NaN          NaN      Belgium        NaN   
32933                      Antwerpen          BEL      Belgium      161.0   
35453                      Antwerpen          BEL      Belgium        NaN   
40958                      Antwerpen          BEL      Belgium        NaN   
40992                            NaN          NaN      Belgium        NaN   
45107                           Nord          FRA      Belgium        NaN   
45113                     Luxembourg          BEL      Belgium      163.0   
54841                            NaN          NaN      Belgium        NaN   
56894                      Antwerpen          BEL      Belgium        NaN   
61189                           R

In [104]:
born19x = bios[bios['born_date'].str.contains(r"^19", na=False)]


In [105]:
born19x

athlete_id                   name   born_date           born_city  \
1                2         Arnaud Boetsch  1969-04-01              Meulan   
5                6      Nicolas Chatelain  1970-01-13              Amiens   
6                7          Patrick Chila  1969-11-27         Ris-Orangis   
7                8           Henri Cochet  1901-12-14        Villeurbanne   
14              15            Damien Éloi  1969-07-04                Vire   
...            ...                    ...         ...                 ...   
145492      149219  Carlos García-Ordóñez  1927-04-24  La Habana (Havana)   
145493      149220     Landysh Falyakhova  1998-08-31    Dva Polya Artash   
145496      149223    Valeriya Merkusheva  1999-09-20     Moskva (Moscow)   
145497      149224        Yuliya Smirnova  1998-05-08              Kotlas   
145499      149814          Bill Phillips  1913-07-15        Dulwich Hill   

                 born_region born_country        NOC  height_cm  weight_kg  \
1                   Yvelines          FRA     France      183.0       76.0   
5                      Somme          FRA     France      181.0       70.0   
6                    Essonne          FRA     France      180.0       73.0   
7                      Rhône          FRA     France        NaN        NaN   
14                  Calvados          FRA     France      165.0       58.0   
...                      ...          ...        ...        ...        ...   
145492   Ciudad de La Habana          CUB       Cuba        NaN        NaN   
145493  Respublika Tatarstan          RUS        ROC        NaN        NaN   
145496                Moskva          RUS        ROC      168.0       65.0   
145497           Arkhangelsk          RUS        ROC      163.0       55.0   
145499       New South Wales          AUS  Australia        NaN        NaN   

         died_date  
1              NaN  
5              NaN  
6              NaN  
7       1987-04-02  
14             NaN  
...            ...  
145492  2019-11-24  
145493         NaN  
145496         NaN  
145497         NaN  
145499  2003-10-20  

[130539 rows x 10 columns]

In [106]:
characters7 = bios[bios['name'].str.contains(r"^.{7}$", na=False)]

In [107]:
characters7

athlete_id     name   born_date  born_city       born_region  \
366            367  Vi Muir  1934-11-04     Duncan  British Columbia   
381            382  He Ying  1977-04-17     Siping             Jilin   
394            395  Hao Wei  1968-10-30        NaN               NaN   
646            649  Ding Yi  1959-01-14   Shanghai          Shanghai   
776            780  Chen Li  1971-03-13   Xiangtan             Hunan   
...            ...      ...         ...        ...               ...   
144401      148091  Liu Jie  1995-04-23  Vancouver  British Columbia   
144402      148092  Luo Jia  1992-11-01    Burnaby  British Columbia   
144422      148113  Rong Ge  2002-08-03        NaN               NaN   
144430      148121  Li Yuxi  1998-09-24   Mianyang           Sichuan   
145483      149210  Feng He  2004-03-31        NaN               NaN   

       born_country                         NOC  height_cm  weight_kg  \
366             CAN                      Canada      170.0        NaN   
381             CHN  People's Republic of China      170.0       68.0   
394             NaN  People's Republic of China      184.0       70.0   
646             CHN                     Austria      166.0       68.0   
776             CHN  People's Republic of China      165.0       60.0   
...             ...                         ...        ...        ...   
144401          CAN  People's Republic of China      180.0       88.0   
144402          CAN  People's Republic of China      179.0       82.0   
144422          NaN  People's Republic of China        NaN        NaN   
144430          CHN  People's Republic of China        NaN        NaN   
145483          NaN  People's Republic of China        NaN        NaN   

       died_date  
366          NaN  
381          NaN  
394          NaN  
646          NaN  
776          NaN  
...          ...  
144401       NaN  
144402       NaN  
144422       NaN  
144430       NaN  
145483       NaN  

[638 rows x 10 columns]