In [4]:
import pandas as pd

print('sdf')

sdf


In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter'],
    'Age': [28, 24, 35],
    'City': ['New York', 'Paris', 'Berlin']
}

df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   28  New York
1   Anna   24     Paris
2  Peter   35    Berlin


In [6]:
df.size

9

In [7]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
print(df)

    Name  Age      City
0   John   28  New York
1   Anna   24     Paris
2  Peter   35    Berlin


In [9]:
import numpy as np

npdata = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(npdata)
print(npdata.shape)
print(npdata.size)
print(npdata.dtype)
print(npdata.ndim)
print(npdata.itemsize)
print(npdata.nbytes)
print(npdata.T)
print(npdata.flatten())
print(npdata.reshape(1, 9))
print(npdata.reshape(3, 3))
print(npdata.reshape(9, 1))
print(npdata.reshape(3, 3, 1))
print(npdata.reshape(3, 3, 1).shape)
print(npdata.reshape(3, 3, 1).ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2
8
72
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)
3


In [10]:
df = pd.read_csv('./warmup-data/coffee.csv')
print(df)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35


In [11]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['A', 'B', 'C'], index=['x', 'y', 'z'])
print(df)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9


In [12]:
df.index

Index(['x', 'y', 'z'], dtype='object')